name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend to Hugging Face Spaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: ${{ secrets.HF_SPACE }} # Format: username/space-name (Contoh: Penelo-page/keluhan-warga-be)
        run: |
          cd backend
          git init
          git checkout -b main
          git config user.name "github-actions-bot"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add .
          git commit -m "deploy: update backend"
          git push -f https://:$HF_TOKEN@huggingface.co/spaces/$HF_SPACE main

  deploy-frontend:
    name: Deploy Frontend to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          cd frontend
          pnpm build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: './frontend/dist'
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
